#!/usr/bin/env python3
"""Setup script for local SQLite database configuration.

This script sets up the local SQLite database for development and testing.
It creates the necessary tables and optionally adds sample data.
"""

import os
import sys

# Default database path
DB_PATH = "tasks.db"


def check_dependencies():
    """Check if required dependencies are installed."""
    print("🔍 Checking dependencies...")
    try:
        import libsql_experimental as libsql
        print("✅ libsql-experimental is installed")
        return True
    except ImportError:
        print("❌ libsql-experimental is not installed")
        print("   Run: pip install libsql-experimental")
        return False


def setup_env_file():
    """Set up the .env file for local development."""
    print("\n📝 Setting up environment file...")
    
    env_path = ".env"
    
    if os.path.exists(env_path):
        print("⚠️  .env file already exists")
        response = input("   Overwrite with local SQLite configuration? (y/n): ").lower().strip()
        if response != 'y':
            print("   Skipping .env file setup")
            return True
    
    # Create a minimal .env for local SQLite
    env_content = """# Local SQLite Configuration
# Generated by setup_local_db.py

# LLM Provider Configuration (optional for basic usage)
# Uncomment and set one of the following:
# OPENAI_API_KEY=your_openai_api_key_here
# LLM_PROVIDER=deepseek
# DEEPSEEK_API_KEY=your_deepseek_api_key_here

# Leave these empty or commented out to use local SQLite
# TURSO_DATABASE_URL=
# TURSO_AUTH_TOKEN=

# Dashboard Configuration
DASHBOARD_HOST=127.0.0.1
DASHBOARD_PORT=5000

# Arcade API Key (optional, for Gmail/Slack integrations)
# ARCADE_API_KEY=your_arcade_api_key_here
"""
    
    with open(env_path, 'w') as f:
        f.write(env_content)
    
    print("✅ Created .env file for local SQLite")
    return True


def create_local_database():
    """Create the local SQLite database with required tables."""
    print("\n🗄️  Creating local SQLite database...")
    
    try:
        import libsql_experimental as libsql
        
        # Remove existing database if user wants to start fresh
        if os.path.exists(DB_PATH):
            response = input(f"   Database '{DB_PATH}' exists. Recreate? (y/n): ").lower().strip()
            if response == 'y':
                os.remove(DB_PATH)
                print(f"   Removed existing {DB_PATH}")
        
        # Connect to local SQLite
        conn = libsql.connect(DB_PATH)
        cursor = conn.cursor()
        
        # Create tasks table
        print("   Creating tasks table...")
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS tasks (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT NOT NULL,
                priority INTEGER NOT NULL,
                due_date TEXT NOT NULL,
                created_at TEXT NOT NULL,
                email_context TEXT,
                embedding F32_BLOB(1536)
            )
        """)
        
        # Create vector index for similarity search
        print("   Creating vector index...")
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS tasks_embedding_idx 
            ON tasks(libsql_vector_idx(embedding))
        """)
        
        conn.commit()
        cursor.close()
        conn.close()
        
        print(f"✅ Local database '{DB_PATH}' created successfully")
        return True
        
    except Exception as e:
        print(f"❌ Error creating database: {str(e)}")
        return False


def add_sample_data():
    """Optionally add sample tasks to the database."""
    print("\n📋 Sample Data Setup")
    response = input("   Add sample tasks to the database? (y/n): ").lower().strip()
    
    if response != 'y':
        print("   Skipping sample data")
        return True
    
    try:
        import libsql_experimental as libsql
        from datetime import datetime, timedelta
        
        conn = libsql.connect(DB_PATH)
        cursor = conn.cursor()
        
        now = datetime.now()
        sample_tasks = [
            ("Review project documentation", 1, (now + timedelta(days=1)).isoformat()),
            ("Update team on progress", 2, (now + timedelta(days=2)).isoformat()),
            ("Complete code review", 1, (now + timedelta(days=1)).isoformat()),
            ("Schedule team meeting", 3, (now + timedelta(days=5)).isoformat()),
            ("Prepare presentation", 2, (now + timedelta(days=3)).isoformat()),
        ]
        
        created_at = now.isoformat()
        for name, priority, due_date in sample_tasks:
            cursor.execute(
                """
                INSERT INTO tasks (name, priority, due_date, created_at, email_context)
                VALUES (?, ?, ?, ?, ?)
                """,
                (name, priority, due_date, created_at, "Sample task")
            )
        
        conn.commit()
        cursor.close()
        conn.close()
        
        print(f"✅ Added {len(sample_tasks)} sample tasks")
        return True
        
    except Exception as e:
        print(f"❌ Error adding sample data: {str(e)}")
        return False


def verify_setup():
    """Verify the database setup is working."""
    print("\n🔧 Verifying setup...")
    
    try:
        import libsql_experimental as libsql
        
        conn = libsql.connect(DB_PATH)
        cursor = conn.cursor()
        
        # Check tables exist
        cursor.execute("""
            SELECT name FROM sqlite_master 
            WHERE type='table' AND name='tasks'
        """)
        
        if cursor.fetchone():
            print("✅ Tasks table exists")
        else:
            print("❌ Tasks table not found")
            return False
        
        # Count tasks
        cursor.execute("SELECT COUNT(*) FROM tasks")
        count = cursor.fetchone()[0]
        print(f"✅ Database contains {count} task(s)")
        
        cursor.close()
        conn.close()
        
        return True
        
    except Exception as e:
        print(f"❌ Verification failed: {str(e)}")
        return False


def print_next_steps():
    """Print next steps for the user."""
    print("\n" + "=" * 50)
    print("🎉 Local SQLite Setup Complete!")
    print("=" * 50)
    print("\nNext steps:")
    print("  1. (Optional) Add your API keys to .env file:")
    print("     - OPENAI_API_KEY for AI-powered features")
    print("     - ARCADE_API_KEY for Gmail/Slack integrations")
    print("\n  2. Start the dashboard:")
    print("     python dashboard.py")
    print("\n  3. Access the dashboard at:")
    print("     http://127.0.0.1:5000")
    print("\n  4. Add tasks manually or run:")
    print("     python main.py")


def main():
    """Main setup function."""
    print("=" * 50)
    print("🗄️  Local SQLite Database Setup")
    print("=" * 50)
    
    # Check dependencies
    if not check_dependencies():
        print("\n❌ Please install dependencies first:")
        print("   pip install -r requirements.txt")
        sys.exit(1)
    
    # Setup .env file
    if not setup_env_file():
        sys.exit(1)
    
    # Create database
    if not create_local_database():
        sys.exit(1)
    
    # Add sample data
    add_sample_data()
    
    # Verify setup
    if not verify_setup():
        sys.exit(1)
    
    # Print next steps
    print_next_steps()


if __name__ == "__main__":
    main()
